# Generated by Django 5.0.6 on 2024-05-19 18:33

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('server', '0003_category_icon'), ('server', '0004_channel_banner_channel_icon')]

    dependencies = [
        ('server', '0002_alter_channel_server_alter_server_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_to),
        ),
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_banner_upload_to),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_icon_upload_to),
        ),
    ]
