# Generated by Django 5.0.6 on 2024-05-19 17:58

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_banner_upload_to),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_icon_upload_to),
        ),
    ]
