# Generated by Django 5.0.6 on 2024-07-02 12:13

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_category_icon_squashed_0004_channel_banner_channel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.channel_icon_upload_to),
        ),
    ]
